# ===============================================================
# NexT Theme Configuration
# See: https://theme-next.js.org/docs/theme-settings/
# ===============================================================

cache:
  enable: true

minify: true

custom_file_path:

# ---------------------------------------------------------------
# Scheme
# ---------------------------------------------------------------
scheme: Muse
darkmode: false

# ---------------------------------------------------------------
# Site Information
# ---------------------------------------------------------------
favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

creative_commons:
  license: by-nc-sa
  size: small
  sidebar: false
  post: false

open_graph:
  enable: true
  options:

# ---------------------------------------------------------------
# Menu
# ---------------------------------------------------------------
menu:
  home: / || fa fa-home
  archives: /archives/ || fa fa-archive

menu_settings:
  icons: true
  badges: false

# ---------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------
sidebar:
  position: left
  display: always
  padding: 18
  offset: 12

avatar:
  url: /images/avatar.png
  rounded: true
  rotated: true

site_state: true

social:
  GitHub: https://github.com/yanni4night || fab fa-github
  E-Mail: mailto:yanni4night@gmail.com || fa fa-envelope

social_icons:
  enable: true
  icons_only: false
  transition: false

links_settings:
  icon: fa fa-globe
  layout: block

links:

toc:
  enable: true
  number: true
  wrap: false
  expand_all: false
  max_depth: 6

# ---------------------------------------------------------------
# Footer
# ---------------------------------------------------------------
language_switcher: false

footer:
  icon:
    name: fa fa-heart
    animated: false
    color: '#ff0000'
  copyright:
  powered: true
  beian:
    enable: false

# ---------------------------------------------------------------
# Post
# ---------------------------------------------------------------
excerpt_description: true
read_more_btn: true

post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true

symbols_count_time:
  separated_meta: true
  item_text_total: false

tag_icon: false

reward_settings:
  enable: false
  animation: false

follow_me:

related_posts:
  enable: false
  icon: fa fa-signs-post

post_edit:
  enable: false

post_navigation: left

tagcloud:
  min: 12
  max: 30
  amount: 200
  orderby: name
  order: 1

calendar:
  calendar_id: <required>
  api_key: <required>
  orderBy: startTime
  showLocation: false
  offsetMax: 72
  offsetMin: 4
  showDeleted: false
  singleEvents: true
  maxResults: 250

# ---------------------------------------------------------------
# Misc
# ---------------------------------------------------------------
preconnect: false

text_align:
  desktop: justify
  mobile: justify

mobile_layout_economy: false

theme_color:
  light: '#222'
  dark: '#222'

body_scrollbar:
  overlay: false
  stable: false

codeblock:
  theme:
    light: default
    dark: stackoverflow-dark
  prism:
    light: prism
    dark: prism-dark
  copy_button:
    enable: false
  fold:
    enable: false
    height: 500

back2top:
  enable: true
  sidebar: false
  scrollpercent: false

reading_progress:
  enable: true
  start_at: left
  position: top
  reversed: false
  color: '#85DB9E'
  height: 3px

bookmark:
  enable: true
  color: '#222'
  save: auto

github_banner:
  enable: true
  permalink: https://github.com/yanni4night

# ---------------------------------------------------------------
# Font
# ---------------------------------------------------------------
font:
  enable: false
  host:
  global:
    external: true
    family: Lato
    size:
  title:
    external: true
    family:
    size:
  headings:
    external: true
    family:
    size:
  posts:
    external: true
    family:
  codes:
    external: true
    family:

# ---------------------------------------------------------------
# SEO
# ---------------------------------------------------------------
index_with_subtitle: false
exturl: false
google_site_verification:
bing_site_verification:
yandex_site_verification:
baidu_site_verification:

# ---------------------------------------------------------------
# Tags
# ---------------------------------------------------------------
note:
  style: simple
  icons: false
  light_bg_offset: 0

tabs:
  sticky: false
  transition:
    tabs: false
    labels: true

pdf:
  enable: false
  height: 500px

mermaid:
  enable: false
  theme:
    light: default
    dark: dark

wavedrom:
  enable: false

# ---------------------------------------------------------------
# Math
# ---------------------------------------------------------------
math:
  every_page: false
  mathjax:
    enable: false
    tags: none
  katex:
    enable: false
    copy_tex: false

# ---------------------------------------------------------------
# External Libraries
# ---------------------------------------------------------------
pjax: true
fancybox: false
mediumzoom: false
lazyload: false
pangu: false

quicklink:
  enable: false
  home: false
  archive: false
  delay: true
  timeout: 3000
  priority: true

# ---------------------------------------------------------------
# Animation
# ---------------------------------------------------------------
motion:
  enable: true
  async: false
  transition:
    menu_item: fadeInDown
    post_block: fadeIn
    post_header: fadeInDown
    post_body: fadeInDown
    coll_header: fadeInLeft
    sidebar: fadeInUp

pace:
  enable: false
  color: blue
  theme: minimal

canvas_ribbon:
  enable: false
  size: 300
  alpha: 0.6
  zIndex: -1

# ---------------------------------------------------------------
# Comments
# ---------------------------------------------------------------
comments:
  style: tabs
  active:
  storage: true
  lazyload: false

disqus:
  enable: true
  shortname: yanni4night
  count: true

disqusjs:
  enable: false

changyan:
  enable: false
  count: true

gitalk:
  enable: false
  distraction_free_mode: true

utterances:
  enable: false

# ---------------------------------------------------------------
# Sharing
# ---------------------------------------------------------------
addtoany:
  enable: false
  buttons:
    - facebook
    - twitter

# ---------------------------------------------------------------
# Analytics
# ---------------------------------------------------------------
google_analytics:
  tracking_id: G-SVVTY641FP
  only_pageview: false

baidu_analytics: 102a03a6de835cd378834b32e2639fbe

growingio_analytics:
cloudflare_analytics:
clarity_analytics:

matomo:
  enable: false

umami:
  enable: false

plausible:
  enable: false

leancloud_visitors:
  enable: false
  security: true

firestore:
  enable: false

busuanzi_count:
  enable: false
  total_visitors: true
  total_visitors_icon: fa fa-user
  total_views: true
  total_views_icon: fa fa-eye
  post_views: true
  post_views_icon: far fa-eye

# ---------------------------------------------------------------
# Search
# ---------------------------------------------------------------
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  unescape: false
  preload: true

# ---------------------------------------------------------------
# Chat
# ---------------------------------------------------------------
chat:
  enable: false
  icon: fa fa-comment

chatra:
  enable: false
  async: true

tidio:
  enable: false

# ---------------------------------------------------------------
# Vendors / CDN
# ---------------------------------------------------------------
vendors:
  internal: local
  plugins: cdnjs
  custom_cdn_url:

css: css
js: js
images: images
